[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@foundry-rs/=lib/foundry-rs/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
